#!/bin/bash
#BSUB -J "TEPID[1-1]%1" 
#BSUB -R "rusage[mem=300000]" 
#BSUB -n 1 
#BSUB -W 10:00 
#BSUB -o log.%J.%I 
#BSUB -e err.%J.%I 


# load the modules 
module load gcc/4.8.2 gdc bowtie2/2.2.6 yaha/0.1.83 perl/5.18.4 samblaster/0.1.22 bedtools/2.25 samtools/1.3 picard-tools/2.0.1 java/1.8.0_91

insertion=/cluster/scratch/crimjhim/zygosity/insertion
absence=/cluster/scratch/crimjhim/zygosity/absence

IDX=$LSB_JOBINDEX
R1=`sed -n ${IDX}p <remaining.step2_5`

# extract sample name, create and enter directory
sample=`basename "$R1"`
echo "sample: $sample"
outputi=/cluster/scratch/crimjhim/zygosity/insertion
outputa=/cluster/scratch/crimjhim/zygosity/absence
#mkdir $sample
output=`basename "$R1" .trim_uniq1.fastq.gz`
outputN="${output}.nosplit.txt"
outputS="${output}.split.txt"
splitbam="${sample}.split1.bam"
nosplitbam="${sample}.nosplit.bam"
splitbed="${sample}.split1.bed"
nosplitbed="${sample}.nosplit.bed"


bedtools bamtobed -i /cluster/scratch/crimjhim/zygosity/$sample/$nosplitbam > $nosplitbed
bedtools intersect -a /cluster/scratch/crimjhim/zygosity/total.absence.txt -b $nosplitbed -wo | bedtools groupby -g 1-3 -c 7,10 -o collapse,collapse > $outputa/$outputN
bedtools intersect -a /cluster/scratch/crimjhim/zygosity/total.insertion.txt -b $nosplitbed -wo | bedtools groupby -g 1-3 -c 7,10 -o collapse,collapse > $outputi/$outputN

bedtools bamtobed -i /cluster/scratch/crimjhim/zygosity/$sample/$splitbam > $splitbed
bedtools intersect -a /cluster/scratch/crimjhim/zygosity/total.absence.txt -b $splitbed -wo | bedtools groupby -g 1-3 -c 7,10 -o collapse,collapse > $outputa/$outputS
bedtools intersect -a /cluster/scratch/crimjhim/zygosity/total.insertion.txt -b $splitbed -wo | bedtools groupby -g 1-3 -c 7,10 -o collapse,collapse > $outputi/$outputS

rm $splitbed
rm $nosplitbed
