#!/bin/bash
#BSUB -J "TEPID[1-1]%1"
#BSUB -R "rusage[mem=70000]"
#BSUB -n 1
#BSUB -W 4:00
#BSUB -o log.%J.%I
#BSUB -e err.%J.%I

IDX=$LSB_JOBINDEX
R1=`sed -n ${IDX}p <remaining.step2_5`

# extract sample name, create and enter directory
sample=`basename "$R1"`
echo "sample: $sample"
insertion=/cluster/project/gdc/people/crimjhim/insertion
absence=/cluster/project/gdc/people/crimjhim/absence

inputinosplit=/cluster/project/gdc/people/crimjhim/compute2/insertion/"${sample}.nosplit.txt"
inputisplit=/cluster/project/gdc/people/crimjhim/compute2/insertion/"${sample}.split.txt"
inputanosplit=/cluster/project/gdc/people/crimjhim/compute2/absence/"${sample}.nosplit.txt"
inputasplit=/cluster/project/gdc/people/crimjhim/compute2/absence/"${sample}.split.txt"

outputi=/cluster/scratch/crimjhim/compute3/output2/"${sample}.insertion.txt"
outputa=/cluster/scratch/crimjhim/compute3/output2/"${sample}.absence.txt"



echo "Processing $sample .."
python zygosity.py $inputisplit $inputinosplit "insertion" > $outputi
echo "Insertion done for $sample .."
python zygosity.py $inputasplit $inputanosplit "absence" > $outputa
echo "Absence done for $sample .."


